### ISSUE TITLE
Symbols not working with images

### ISSUE THREAD

**Issue by r-ss-ll** [preciousforever/sketch-data-populator#53]
I have my symbol on my Symbols page with placeholder text and image, then when I populate symbols on my page I'm designing on with JSON the text is populated, but the image remains as a grey box.

**Comment by lukasondrej** [comment]
Thanks for letting us know - this issue was caused by shape layers with image fill not getting populated. It should now be fixed, please check the latest commit in the new-symbols-support branch.

**Comment by r-ss-ll** [comment]
I'm still getting a bit of a bug. When I populate my symbols the image doesn't appear. I have to manually set the master symbol rectangle to have a background image set to fill. Then when I populate my symbols in my design page the fill image in the symbol is replaced with the json data. I really appreciate your work on this.

**Comment by nitrada** [comment]
wasn't this always the case, @lukasondrej? maybe there's a way to get rid of the need to set the background type to image as soon as we knock on a shape's door with an image in our pocket :)

**Comment by lukasondrej** [comment]
@nitrada I think with the previous versions of Sketch, it was done automatically but doesn't seem to be with the new symbols. It should be possible to automatically set the background as image when there's an image available, I'll investigate that.

**Comment by nitrada** [comment]
@lukasondrej great 👍
